name: npm-publish
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm build
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: 'v%s'
          tag_message: 'v%s'
          create_tag: 'true'
          commit_pattern: "^Release (\\S+)"
          workspace: '.'
          publish_command: 'yarn'
          publish_args: '--non-interactive'
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
